# Generated by Django 3.1.3 on 2022-05-01 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('sync', 'Sync'), ('async', 'Async')], default='async', max_length=32)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('job_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('input_file', models.CharField(default='', max_length=255)),
                ('job_submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
