# Generated by Django 3.1.3 on 2022-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superresolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='out_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=32),
        ),
    ]
